# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, null=True)),
                ('class_enrolled', models.IntegerField()),
                ('preferred_subject', models.CharField(max_length=10, null=True)),
                ('marks_obtained', models.IntegerField()),
            ],
        ),
    ]
